### ISSUE TITLE
error in `embed_cat_prop_plot()` with dev version of ggiraph and ggplot2

### ISSUE THREAD

**Issue by davidgohel** [NIFU-NO/saros#258]
Hello,

With the dev version of ggiraph and ggplot2, an error occurs in `embed_cat_prop_plot()`. That has been spotted by a revdep check.

A new version of ggplot2 (`3.5.0`) is being prepared. It has an impact on ggiraph that must be updated.

```r
remotes::install_github("tidyverse/ggplot2", ref = "rc/3.5.0")
remotes::install_github("davidgohel/ggiraph", ref = "pr-269")
```

With this new version, a change has to be made in your package at this line https://github.com/NIFU-NO/saros/blob/42cef6f67ead583e1514435518223440e5a8e1fd/R/cat_prop_plot_html.R#L142

It must now be:

```
text = ggplot2::element_text(family = dots$font_family)
```

The error is:

```
Browse[1]> c
Error in `setup_elements()` at ggplot2-rc-3.5.0/R/ggproto.R:180:17:
! Can't merge the `text` theme element.
Caused by error in `merge_element()` at ggplot2-rc-3.5.0/R/theme.R:589:7:
! Only elements of the same class can be merged.
Run `rlang::last_trace()` to see where the error occurred.
```

It's because `ggplot2:::merge_element.element()` does not allow the merge of objects of class`element_text()` and `element_text_interactive()`.

I am not sure that this would break any functionality, but you must know better that I do... 

Are you ok to do this change (I can also submit a PR if you want)

KR,
David

**Comment by sda030** [comment]
Hi David, thanks for the note.
Does this imply that all the `ggiraph::element_*_interactive()` =>
`ggplot2::element_*()`, or similar broader changes?

I can PR it within the next few days together with some other fixes.

Stephan

man. 12. feb. 2024 kl. 00:30 skrev David Gohel ***@***.***>:

**Comment by davidgohel** [comment]
No I don't think, I think it only applies to specific case `theme(text = ggiraph::element_text_interactive())`, maybe `theme(line, rect)` as it usually generate a call to `merge_element.element()`.

I don't know yet (I discover the issue yesterday) if it is possible for 'ggiraph' to implement its own `merge_element.element()` in order to pass this... But I will probably want to send a new version to CRAN as soon as ggplot 3.5 get on CRAN and take time after that to improve a new version of 'ggiraph'

**Comment by sda030** [comment]
Sounds reasonable. Again, thanks for the notice!
